BEGIN TRANSACTION;
DROP TABLE IF EXISTS CIDADES;

CREATE TABLE CIDADES
(
    CIDADE_ID INTEGER PRIMARY KEY,
    CIDADE_NOME TEXT NOT NULL
);

DROP TABLE IF EXISTS PESSOAS;

CREATE TABLE PESSOAS
(
    PESSOA_ID INTEGER PRIMARY KEY,
    PESSOA_NOME TEXT NOT NULL,
    PESSOA_IDADE TEXT NOT NULL,
    PESSOA_CIDADE_ID INT NOT NULL
);
INSERT INTO CIDADES (CIDADE_NOME) VALUES 

    ('São Bernardo do Campo'),
    ('Joinville'),
    ('Santo Andre');


INSERT INTO PESSOAS (PESSOA_NOME, PESSOA_IDADE, PESSOA_CIDADE_ID) VALUES 

('Matheus',23,2),
('Amanda',21,1),
('Alexandre',50,2),
('Alexandre',23,1),
('Cassia',40,1),
('Bruno',35,3),
('Hugo',38,1);

COMMIT;
SELECT * FROM PESSOAS WHERE PESSOA_NOME LIKE '';