DROP TABLE IF EXISTS PRODUTOS;

CREATE TABLE PRODUTOS 
(
    PRODUTO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRODUTO_NOME TEXT  NOT NULL ,
    PRATELEIRA_ID INTEGER,
    PRODUTO_QUANTIDADE INTEGER, 
    PRODUTO_VALOR FLOAT  NOT NULL DEFAULT '0', 
    FOREIGN KEY (PRATELEIRA_ID) REFERENCES PRATELEIRAS(PRATELEIRA_ID)
);

DROP TABLE IF EXISTS PRATELEIRAS;

CREATE TABLE PRATELEIRAS 
(
    PRATELEIRA_ID INTEGER  PRIMARY KEY AUTOINCREMENT ,
    PRATELEIRA_NOME TEXT  NOT NULL ,
    PRATELEIRA_LOCALIZACAO CHAR  NOT NULL

);

DROP TABLE IF EXISTS ITENS_CUPOM_FISCAL;

CREATE TABLE ITENS_CUPOM_FISCAL 
(
    ITEM_CUPOM_FISCAL_ID INTEGER  PRIMARY KEY AUTOINCREMENT ,
    ITEM_CUPOM_FISCAL_NUMERO INTEGER,
    ITEM_CUPOM_FISCAL_SEQUENCIA INTEGER NOT NULL ,
    ITEM_CUPOM_FISCAL_PRODUTO_ID INTEGER NOT NULL,
    ITEM_CUPOM_FISCAL_PRODUTO INTEGER  NOT NULL ,
    ITEM_CUPOM_FISCAL_QUANTIDADE INTEGER  NOT NULL ,
    ITEM_CUPOM_FISCAL_VALOR_UN INTEGER  NOT NULL DEFAULT '0',
    ITEM_CUPOM_FISCAL_VALOR_TOT INTEGER  NOT NULL DEFAULT '0',
    ITEM_CUPOM_FISCAL_NOTA_ID INTEGER NOT NULL,
    FOREIGN KEY (ITEM_CUPOM_FISCAL_PRODUTO_ID) REFERENCES PRODUTOS(PRODUTO_ID),
    FOREIGN KEY (ITEM_CUPOM_FISCAL_NOTA_ID) REFERENCES NOTAS(NOTA_ID)
);

DROP TABLE IF EXISTS ATENDENTES;

CREATE TABLE ATENDENTES 
(
    ATENDENTE_CODIGO INTEGER  PRIMARY KEY AUTOINCREMENT ,
    ATENDENTE_NOME TEXT NOT NULL  
);

DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES (
    CLIENTE_ID INTEGER  PRIMARY KEY AUTOINCREMENT ,
    CLIENTE_NOME TEXT NOT NULL ,
    CLIENTE_TELEFONE INTEGER NOT NULL ,
    CLIENTE_CPF INTEGER NOT NULL ,
    CLIENTE_TOTAL_COMPRAS INTEGER NOT NULL,
    CIDADE_ID INTEGER NOT NULL,
    FOREIGN KEY (CIDADE_ID) REFERENCES CIDADES(CIDADE_ID)
);

DROP TABLE IF EXISTS NOTAS;
CREATE TABLE NOTAS 
(
    NOTA_ID INTEGER NOT NULL , 
    NOTA_DATA_DE_EMISSAO TEXT NOT NULL ,
    NOTA_CLIENTE_ID INTEGER NOT NULL,
    NOTA_ATENDENTE_ID INTEGER NOT NULL,
    FOREIGN KEY (NOTA_CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID),
    FOREIGN KEY (NOTA_ATENDENTE_ID) REFERENCES ATENDENTES(ATENDENTE_ID)
    );

DROP TABLE IF EXISTS CIDADES;
CREATE TABLE CIDADES

(
CIDADE_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
CIDADE_NOME TEXT NOT NULL,
CIDADE_CEP TEXT NOT NULL
);