BEGIN TRANSACTION;

DROP TABLE IF EXISTS PESSOAS;

CREATE TABLE PESSOAS
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    IDADE INT NOT NULL,
    CIDADE_ID TEXT
);
COMMIT;

BEGIN TRANSACTION;

INSERT INTO PESSOAS (ID,NOME,IDADE) VALUES (1,'Matheus',23);
