BEGIN TRANSACTION;

DROP TABLE IF EXISTS PESSOAS;

CREATE TABLE PESSOAS
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    IDADE INT NOT NULL,
    CIDADE_ID TEXT
);
COMMIT;

BEGIN TRANSACTION;

INSERT INTO PESSOAS (NOME,IDADE) VALUES ('Matheus',23), ('Amanda',22);

UPDATE PESSOAS
SET IDADE = 25 WHERE ID = 1;

SELECT * FROM PESSOAS;